from __future__ import annotations


API_KEY_ENV = "LECTURECAST_API_KEY"
DIRECTOR_URL_ENV = "LECTURECAST_DIRECTOR_URL"
KEYRING_SERVICE = "agentmesh-lecturecast"
KEYRING_USERNAME = "api-key"
PROJECT_DIRECTORY = ".lecturecast"
PROJECT_SCHEMA_VERSION = "1.0"
CLIENT_VERSION = "0.3.2"
